spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:h2:mem:book-explorer
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

  flyway:
    locations: classpath:db/migrations
    enabled: false

logging:
  level:
    org.book.explorer: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    root: WARN